// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class CloudSchedulerTransport: CloudSchedulerStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://cloudscheduler.googleapis.com",
      )
    }

    public func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.ListJobsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/jobs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSchedulerV1.ListJobsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/jobs"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.job {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateJob(
      request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.job.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.job.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.job {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func pauseJob(
      request: PauseJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):pause"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func resumeJob(
      request: ResumeJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):resume"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func runJob(
      request: RunJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):run"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSchedulerV1.Job.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/locations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
