// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol CloudSchedulerStub: Sendable {
    func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.ListJobsResponse

    func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func updateJob(
      request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func pauseJob(
      request: PauseJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func resumeJob(
      request: ResumeJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func runJob(
      request: RunJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSchedulerV1.Job

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
