// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CreateJob][google.cloud.scheduler.v1.CloudScheduler.CreateJob].
///
/// [google.cloud.scheduler.v1.CloudScheduler.CreateJob]: <doc:CloudScheduler/createJob(request:)>
public struct CreateJobRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The location name. For example:
  /// `projects/PROJECT_ID/locations/LOCATION_ID`.
  public var parent: Swift.String = Swift.String()

  /// Required. The job to add. The user can optionally specify a name for the
  /// job in [name][google.cloud.scheduler.v1.Job.name].
  /// [name][google.cloud.scheduler.v1.Job.name] cannot be the same as an
  /// existing job. If a name is not specified then the system will
  /// generate a random unique name that will be returned
  /// ([name][google.cloud.scheduler.v1.Job.name]) in the response.
  ///
  /// [google.cloud.scheduler.v1.Job.name]: <doc:Job/name>
  public var job: Job? = nil

  /// Initialize a new instance of `CreateJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateJobRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.scheduler.v1.CreateJobRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
