// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for listing jobs using
/// [ListJobs][google.cloud.scheduler.v1.CloudScheduler.ListJobs].
///
/// [google.cloud.scheduler.v1.CloudScheduler.ListJobs]: <doc:CloudSchedulerClient/listJobs(request:)>
public struct ListJobsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The location name. For example:
  /// `projects/PROJECT_ID/locations/LOCATION_ID`.
  public var parent: Swift.String = Swift.String()

  /// Requested page size.
  ///
  /// The maximum page size is 500. If unspecified, the page size will
  /// be the maximum. Fewer jobs than requested might be returned,
  /// even if more jobs exist; use next_page_token to determine if more
  /// jobs exist.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying a page of results the server will return. To
  /// request the first page results, page_token must be empty. To
  /// request the next page of results, page_token must be the value of
  /// [next_page_token][google.cloud.scheduler.v1.ListJobsResponse.next_page_token]
  /// returned from the previous call to
  /// [ListJobs][google.cloud.scheduler.v1.CloudScheduler.ListJobs].
  ///
  /// [google.cloud.scheduler.v1.CloudScheduler.ListJobs]: <doc:CloudSchedulerClient/listJobs(request:)>
  /// [google.cloud.scheduler.v1.ListJobsResponse.next_page_token]: <doc:ListJobsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListJobsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListJobsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.scheduler.v1.ListJobsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
