// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Settings that determine the retry behavior.
///
/// By default, if a job does not complete successfully (meaning that
/// an acknowledgement is not received from the handler, then it will be retried
/// with exponential backoff according to the settings in
/// [RetryConfig][google.cloud.scheduler.v1.RetryConfig].
///
/// [google.cloud.scheduler.v1.RetryConfig]: <doc:RetryConfig>
public struct RetryConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of attempts that the system will make to run a job using the
  /// exponential backoff procedure described by
  /// [max_doublings][google.cloud.scheduler.v1.RetryConfig.max_doublings].
  ///
  /// The default value of retry_count is zero.
  ///
  /// If retry_count is 0, a job attempt will not be retried if
  /// it fails. Instead the Cloud Scheduler system will wait for the
  /// next scheduled execution time. Setting retry_count to 0 does not prevent
  /// failed jobs from running according to schedule after the failure.
  ///
  /// If retry_count is set to a non-zero number then Cloud Scheduler
  /// will retry failed attempts, using exponential backoff,
  /// retry_count times, or until the next scheduled execution time,
  /// whichever comes first.
  ///
  /// Values greater than 5 and negative values are not allowed.
  ///
  /// [google.cloud.scheduler.v1.RetryConfig.max_doublings]: <doc:RetryConfig/maxDoublings>
  public var retryCount: Swift.Int32 = Swift.Int32()

  /// The time limit for retrying a failed job, measured from time when an
  /// execution was first attempted. If specified with
  /// [retry_count][google.cloud.scheduler.v1.RetryConfig.retry_count], the job
  /// will be retried until both limits are reached.
  ///
  /// The default value for max_retry_duration is zero, which means retry
  /// duration is unlimited.
  ///
  /// [google.cloud.scheduler.v1.RetryConfig.retry_count]: <doc:RetryConfig/retryCount>
  public var maxRetryDuration: GoogleCloudWkt.Duration? = nil

  /// The minimum amount of time to wait before retrying a job after
  /// it fails.
  ///
  /// The default value of this field is 5 seconds.
  public var minBackoffDuration: GoogleCloudWkt.Duration? = nil

  /// The maximum amount of time to wait before retrying a job after
  /// it fails.
  ///
  /// The default value of this field is 1 hour.
  public var maxBackoffDuration: GoogleCloudWkt.Duration? = nil

  /// The time between retries will double `max_doublings` times.
  ///
  /// A job's retry interval starts at
  /// [min_backoff_duration][google.cloud.scheduler.v1.RetryConfig.min_backoff_duration],
  /// then doubles `max_doublings` times, then increases linearly, and finally
  /// retries at intervals of
  /// [max_backoff_duration][google.cloud.scheduler.v1.RetryConfig.max_backoff_duration]
  /// up to [retry_count][google.cloud.scheduler.v1.RetryConfig.retry_count]
  /// times.
  ///
  /// For example, if
  /// [min_backoff_duration][google.cloud.scheduler.v1.RetryConfig.min_backoff_duration]
  /// is 10s,
  /// [max_backoff_duration][google.cloud.scheduler.v1.RetryConfig.max_backoff_duration]
  /// is 300s, and `max_doublings` is 3, then the job will first be retried in
  /// 10s. The retry interval will double three times, and then increase linearly
  /// by 2^3 * 10s.  Finally, the job will retry at intervals of
  /// [max_backoff_duration][google.cloud.scheduler.v1.RetryConfig.max_backoff_duration]
  /// until the job has been attempted
  /// [retry_count][google.cloud.scheduler.v1.RetryConfig.retry_count] times.
  /// Thus, the requests will retry at 10s, 20s, 40s, 80s, 160s, 240s, 300s,
  /// 300s, ....
  ///
  /// The default value of this field is 5.
  ///
  /// [google.cloud.scheduler.v1.RetryConfig.max_backoff_duration]: <doc:RetryConfig/maxBackoffDuration>
  /// [google.cloud.scheduler.v1.RetryConfig.min_backoff_duration]: <doc:RetryConfig/minBackoffDuration>
  /// [google.cloud.scheduler.v1.RetryConfig.retry_count]: <doc:RetryConfig/retryCount>
  public var maxDoublings: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `RetryConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RetryConfig().with { $0.retryCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.scheduler.v1.RetryConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
